name: Keep Supabase Database Alive

on:
  schedule:
    # Run every 6 days at 2 AM UTC (before the 7-day pause threshold)
    - cron: '0 2 */6 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    environment: production  # Add this line if using environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run keep-alive script
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      run: node dev-tests/keep-alive.js
      
    - name: Report status
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Database keep-alive successful at $(date)"
        else
          echo "❌ Database keep-alive failed at $(date)"
          exit 1
        fi
